version: '3'

services:
    mysql:
        image: mysql
        ports:
            - "3308:3306"
        volumes:
            - ./:/share
        environment:
            MYSQL_ROOT_PASSWORD: doctrine
            MYSQL_USER: doctrine
            MYSQL_PASSWORD: doctrine
            MYSQL_DATABASE: doctrine-active-record